theme = "starlight"
# theme = "base16_terminal"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
true-color = true

[editor.search]
# smart-case = false  # uncomment to make search fully case sensitive

[editor.cursor-shape]
# insert = "bar"

[editor.file-picker]
hidden = false

# [editor.whitespace]
# render = "all"
#
# or control each character
#
[editor.whitespace.render]
space = "all"
tab = "all"
# nbsp = "none"
# nnbsp = "none"
# newline = "none"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
# tab = "→"
# newline = "⏎"
# tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.soft-wrap]
enable = true

[editor.statusline]
center = ["version-control", "separator", "file-type"]
right = [
  "diagnostics",
  "selections",
  "register",
  "position-percentage",
  "position",
  "file-encoding",
]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
space.B = ":sh git blame -L %{cursor_line},+1 %{buffer_name}"
#C-s = ":write"                                         # Ctrl and 's' to write
#y = ":clipboard-yank"
#d = ["yank_to_clipboard", "delete_selection_noyank"]
#p = ":clipboard-paste-after"
#P = ":clipboard-paste-before"
# Pop up window with the current line's git blame information.

[keys.select]
#y = ":clipboard-yank"
#d = ["yank_to_clipboard", "delete_selection_noyank"]
#p = ":clipboard-paste-after"
#P = ":clipboard-paste-before"

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode
