# toml
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true


# markdown
[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true


# Bash
[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["-i", "4"] }
auto-format = true


# C
# Install C lsp and formatter:
#   sudo apt install clangd clang-format
[[language]]
name = "c"
formatter = { command = "clang-format" }
auto-format = true


# Rust
# Install rust:
#   curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# Install rust lsp `rust-analyzer':
#   rustup component add rust-analyzer
[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["--edition=2024"] }
auto-format = true


# Python
[[language]]
name = "python"
formatter = { command = "black", args = ["-q", "-"] }
auto-format = true


# JavaScript
[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "oxlint"]
auto-format = true
formatter = { command = "prettier", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }


# Typescript
[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "oxlint"]
auto-format = true
formatter = { command = "prettier", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }
