[colors.primary]
background = '#23283c'
foreground = '#ced1e6'

[colors.normal]
black = '#23283c'
red = '#eb2260'
green = '#1ae186'
yellow = '#92734c'
blue = '#12488b'
magenta = '#9347ba'
cyan = '#2aa1b3'
white = '#ced1e6'

[colors.bright]
black = '#5e5c64'
red = '#f17da1'
green = '#b0eb79'
yellow = '#e3c083'
blue = '#7bb7ff'
magenta = '#c061cb'
cyan = '#8ec07c'
white = '#ebdbb2'

[colors]
transparent_background_colors = true

[window]
decorations = "Full"
# decorations = "None"
# opacity = 0.9
# startup_mode = "Fullscreen"

[window.dimensions]
columns = 96
lines = 24

[window.padding]
x = 2
y = 2

[window.position]
#x = 1920
x = 0
y = 0

[font]
normal.family = "JetBrains Mono Nerd Font"
# normal.family = "SauceCodePro Nerd Font"
# normal.family = "Hurmit Nerd Font"
# normal.family = "Agave Nerd Font"
# normal.style = "Regular"
size = 16

[shell]
program = "/bin/bash"

#[terminal.shell]
#program = "/bin/bash"

[selection]
save_to_clipboard = true

[cursor.style]
shape = 'Block'  # Block | Underline | Beam
blinking = 'Off' # Never | Off | On | Always

[cursor]
blink_interval = 500
blink_timeout = 5
